name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Remove existing images
        run: |
          IMAGE_IDS=$(docker images -q)
          if [ -n "$IMAGE_IDS" ]; then
            docker rmi -f $IMAGE_IDS
          else
            echo "No images to remove."
          fi

      - name: Build and push backend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/mern-backend:latest ./backend
          docker push $DOCKERHUB_USERNAME/mern-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/mern-frontend:latest ./frontend
          docker push $DOCKERHUB_USERNAME/mern-frontend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
     - name: Checkout repo
       uses: actions/checkout@v3

     - name: Create .env file
       run: |
        echo "PORT=${{ secrets.PORT }}" > .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
        echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
        echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env

    #  - name: Remove old backend image
    #    run: |
    #     docker rmi -f ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest || true

    #  - name: Remove old frontend image
    #    run: |
    #     docker rmi -f ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest || true

    #  - name: Pull latest backend image
    #    run: docker pull ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

    #  - name: Pull latest frontend image
    #    run: docker pull ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest

     - name: Stop and remove old containers
       run: docker-compose down

     - name: Start containers with latest images
       run: docker-compose up -d --remove-orphans
