name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Log in to Docker Hub
        run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/mern-backend:latest ./backend
          docker push $DOCKERHUB_USERNAME/mern-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/mern-frontend:latest ./frontend
          docker push $DOCKERHUB_USERNAME/mern-frontend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
     - name: Pull latest backend image
       run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest

     - name: Pull latest frontend image
       run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:latest

     - name: Stop and remove old containers
       run: docker-compose down

     - name: Start containers with latest images
       run: docker-compose up -d --remove-orphans
